### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by sballesteros** [w3c/webvtt.js#14]
Could you publish the package to npm ?

**Comment by annevk** [comment]
If you can tell me how, or you can do it for me, that'd be great.

**Comment by monicao** [comment]
@annevk It's pretty simple, you can just use a command-line tool to do it.

Here is a link to a step-by-step guide: https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by Ryan-Haines** [comment]
Readme should be updated from `webvtt-parser` to `node-webvtt`. Thanks for the package!

**Comment by annevk** [comment]
That looks like https://github.com/osk/node-webvtt, which I guess is a fork of sorts.

**Comment by osk** [comment]
`node-webvtt` has it's own parser that's not as extensive as this one but I'm open to extending or accepting PRs 😄

**Comment by elsassph** [comment]
Hmm guys, publish to npm maybe?

**Comment by dontcallmedom** [comment]
done https://www.npmjs.com/package/webvtt-parser
