### ISSUE TITLE
Adding a license to this project

### ISSUE THREAD

**Issue by NgoniChoga** [w3c/webvtt.js#18]
Would it be possible to add an open source licence to this project as it would help us when using this project in major open-source projects.

Thanks.

**Comment by annevk** [comment]
It's licensed under CC0 as expressed in the files. I'd accept a PR that adds a LICENSE file to that effect though.

**Comment by dontcallmedom** [comment]
now done https://github.com/w3c/webvtt.js/blob/master/LICENSE.md
