### ISSUE TITLE
Style block incorrectly interpreted as cue

### ISSUE THREAD

**Issue by davemevans** [w3c/webvtt.js#27]
Attemping to parse EXAMPLE 3 from https://w3c.github.io/webvtt/#styling gives the following:
```
Line 4: Cue identifier needs to be followed by timestamp.
Line 13: Cue identifier needs to be followed by timestamp.
```

It seems that the header parser misinterpets the style block as a cue.

**Comment by jpeurich** [comment]
Same problem exists 2 June 2021.  Very frustrating bug.
