### ISSUE TITLE
CDN for quick usage

### ISSUE THREAD

**Issue by kocoten1992** [w3c/webvtt.js#30]
Hi, thanks for the library!

Do we publish on any CDN (eg: cdnjs, jsdelivr...) for quick grab the link and use fashion, do we plan to support that in the future ?

**Comment by dontcallmedom** [comment]
filed https://github.com/cdnjs/packages/issues/1312

**Comment by dontcallmedom** [comment]
and now published https://cdnjs.com/libraries/webvtt-parser
