### ISSUE TITLE
wrong warning: 'No blank line after the signature' 

### ISSUE THREAD

**Issue by ApayRus** [w3c/webvtt.js#32]
How I know, after a first line  starting with WEBVTT it is ok to have whole paragraph with some data, like, lang, author etc. 
But your validator throws an error: `No blank line after the signature`, asking to add blank line after first line... 

In my opinion, it is a valid VTT: 

![Screenshot from 2021-07-04 06-14-54](https://user-images.githubusercontent.com/1222611/124371943-46ba9880-dc8f-11eb-973e-87b534587ccc.png)

**Comment by dontcallmedom** [comment]
The [spec doesn't allow non-empty lines](https://w3c.github.io/webvtt/#file-structure) after the WebVTT signature, so the validator is correct.

There has been a [proposal to change the spec to allow this](https://github.com/w3c/webvtt/issues/485), but it hasn't been approved yet as far as I can tell.
