### ISSUE TITLE
Online version is outdated

### ISSUE THREAD

**Issue by Frenzie** [w3c/webvtt.js#37]
The version at https://quuz.org/webvtt/ is not using the latest version of the script.

I ran into a https://github.com/w3c/webvtt.js/commit/b2b842c569170b8ff80f88f24ac528629f7aeaa7 and determined it was a bug, but when I went to fix it… well, it'd already been fixed. :-)

**Comment by dontcallmedom** [comment]
cc @annevk who I believe maintain the online version

**Comment by Frenzie** [comment]
Hah, I completely forgot about that and didn't make the connection but I think I knew that about quuz once. What's up Anne? Long time no see ('07?). ;-)

**Comment by annevk** [comment]
Heya, long time indeed. 😊

I'm no longer maintaining it. Since it's just a script it might be possible to use GitHub Pages. I'd be happy to set up a redirect (perhaps 302 since it's GitHub Pages and not a nice stable URL) once that's in place.

**Comment by dontcallmedom** [comment]
I've set up https://w3c.github.io/webvtt.js/parser.html with github pages

**Comment by annevk** [comment]
The URL in OP now redirects, so closing.
